// USER ACTIONS
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';

// CART ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const INCREASE_QNTY = 'INCREASE_QNTY';
export const DECREASE_QNTY = 'DECREASE_QNTY';

// PRODUCT ACTIONS
export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const UPDATE_PRODUCTS = 'APPEND_PRODUCTS';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const FETCHING_CATEGORIES = 'FETCHING_CATEGORIES';
